# Generated by Django 4.1 on 2023-10-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='operation_id')),
                ('room_id', models.CharField(max_length=10, verbose_name='room_id')),
                ('user_id', models.CharField(max_length=30, verbose_name='user_id')),
                ('temp', models.IntegerField(verbose_name='温度')),
                ('wind_speed', models.IntegerField(verbose_name='wind_speed')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='user_id')),
                ('user_name', models.CharField(max_length=20, verbose_name='user_name')),
                ('user_sex', models.CharField(max_length=10, verbose_name='user_sex')),
                ('user_age', models.IntegerField(verbose_name='user_age')),
                ('live_time', models.DateTimeField(auto_now=True)),
                ('user_phone', models.CharField(max_length=20, verbose_name='user_phone')),
                ('room_id', models.CharField(max_length=10, verbose_name='room_id')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
