# Generated by Django 4.1 on 2023-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='request_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='operation_id'),
        ),
    ]
