# Generated by Django 3.2.22 on 2023-12-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(choices=[(3, 'HIGH'), (2, 'MIDDLE'), (1, 'LOW')], default=2, verbose_name='风速'),
        ),
        migrations.AlterField(
            model_name='room',
            name='target_temp',
            field=models.IntegerField(default=22.0, verbose_name='目标温度'),
        ),
    ]
