# Generated by Django 4.1 on 2023-10-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='live_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_sex',
        ),
    ]
