# Generated by Django 3.2.22 on 2023-12-02 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fee_rate',
            field=models.FloatField(default=0.0, verbose_name='费率'),
        ),
        migrations.AddField(
            model_name='room',
            name='sever_begin_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='服务开始时间'),
        ),
        migrations.AddField(
            model_name='room',
            name='sever_over_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='服务结束时间'),
        ),
    ]
