# Generated by Django 4.1 on 2023-10-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_live_time_remove_user_room_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCondition',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='room_id')),
                ('user_id', models.CharField(max_length=20, verbose_name='user_id')),
                ('temp', models.IntegerField(verbose_name='温度')),
                ('wind_speed', models.IntegerField(verbose_name='wind_speed')),
            ],
            options={
                'db_table': 'AirCondition',
            },
        ),
        migrations.RenameField(
            model_name='room',
            old_name='operation_id',
            new_name='request_id',
        ),
        migrations.AddField(
            model_name='room',
            name='change_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='close_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='open_time',
            field=models.DateTimeField(null=True),
        ),
    ]
