# Generated by Django 3.2.22 on 2023-12-02 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231202_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_temp',
            field=models.IntegerField(default=26.0, verbose_name='当前温度'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(choices=[(3, 'HIGH'), (2, 'MIDDLE'), (1, 'LOW')], default=0, verbose_name='风速'),
        ),
        migrations.AlterField(
            model_name='room',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 6, 25, 58, 158554, tzinfo=utc), verbose_name='请求发出时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sever_begin_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 6, 25, 58, 158554, tzinfo=utc), verbose_name='服务开始时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sever_over_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 6, 25, 58, 158554, tzinfo=utc), verbose_name='服务结束时间'),
        ),
    ]
