# Generated by Django 4.1 on 2023-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_room_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='operation_id'),
        ),
    ]
