# Generated by Django 3.2.22 on 2023-12-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231206_1910'),
        ('user', '0003_alter_room_fan_speed_alter_room_state'),
    ]

    operations = [
    ]
