# Generated by Django 4.1 on 2023-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_aircondition_rename_operation_id_room_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=30, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='room_id',
            field=models.CharField(default=1, max_length=10, verbose_name='room_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
