# Generated by Django 3.2.22 on 2023-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_user_age_remove_user_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirCondition',
        ),
        migrations.RemoveField(
            model_name='room',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='room',
            name='current_temp',
            field=models.IntegerField(default=25.0, verbose_name='当前温度'),
        ),
        migrations.AddField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(default=2, verbose_name='wind_speed'),
        ),
        migrations.AddField(
            model_name='room',
            name='fee',
            field=models.FloatField(default=0.0, verbose_name='费用'),
        ),
        migrations.AddField(
            model_name='room',
            name='init_temp',
            field=models.IntegerField(default=0.0, verbose_name='初始温度'),
        ),
        migrations.AddField(
            model_name='room',
            name='operation',
            field=models.IntegerField(choices=[(1, '调温'), (2, '调风'), (3, '开机'), (4, '关机')], default=0, verbose_name='操作类型'),
        ),
        migrations.AddField(
            model_name='room',
            name='scheduling_num',
            field=models.IntegerField(default=0, verbose_name='调度次数'),
        ),
        migrations.AddField(
            model_name='room',
            name='serve_time',
            field=models.IntegerField(default=0, verbose_name='当前服务时长'),
        ),
        migrations.AddField(
            model_name='room',
            name='wait_time',
            field=models.IntegerField(default=0, verbose_name='当前等待时长'),
        ),
        migrations.AddField(
            model_name='user',
            name='begin_date',
            field=models.DateField(auto_now=True, max_length=30, verbose_name='begin_data'),
        ),
        migrations.AddField(
            model_name='user',
            name='out_date',
            field=models.DateTimeField(auto_now=True, max_length=30, verbose_name='out_data'),
        ),
    ]
