# Generated by Django 3.2.22 on 2023-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20231207_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(choices=[(3, 'high'), (2, 'middel'), (1, 'low')], default=2, verbose_name='风速'),
        ),
    ]
