# Generated by Django 3.2.22 on 2023-11-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231117_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='target_temp',
            field=models.IntegerField(default=0.0, verbose_name='目标温度'),
        ),
    ]
