# Generated by Django 3.2.22 on 2023-12-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_room_request_id'),
        ('user', '0005_auto_20231203_1330'),
    ]

    operations = [
    ]
