# Generated by Django 3.2.22 on 2023-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_room_target_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevringQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_num', models.IntegerField(default=0, verbose_name='服务对象数')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_num', models.IntegerField(default=0, verbose_name='等待对象数')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.IntegerField(choices=[(1, 'SERVING'), (2, 'WAITING'), (3, 'SHUTDOWN'), (4, 'BACKING')], default=3, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(choices=[(3, 'HIGH'), (2, 'MIDDLE'), (1, 'LOW')], default=2, verbose_name='风速'),
        ),
    ]
