# Generated by Django 3.2.22 on 2023-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20231204_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='init_temp',
            field=models.IntegerField(default=22.0, verbose_name='初始温度'),
        ),
        migrations.AlterField(
            model_name='room',
            name='request_time',
            field=models.DateTimeField(verbose_name='请求发出时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sever_begin_time',
            field=models.DateTimeField(verbose_name='服务开始时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sever_over_time',
            field=models.DateTimeField(verbose_name='服务结束时间'),
        ),
    ]
