# Generated by Django 4.1 on 2023-11-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20231117_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SevringQueue',
        ),
        migrations.DeleteModel(
            name='WaitingQueue',
        ),
        migrations.AlterField(
            model_name='user',
            name='begin_date',
            field=models.DateField(auto_now=True, max_length=30, verbose_name='begin_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='out_date',
            field=models.DateTimeField(auto_now=True, max_length=30, verbose_name='out_date'),
        ),
    ]
