# Generated by Django 3.2.22 on 2023-11-30 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20231117_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SevringQueue',
        ),
        migrations.DeleteModel(
            name='WaitingQueue',
        ),
        migrations.AddField(
            model_name='room',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求发出时间'),
        ),
    ]
