# Generated by Django 3.2.22 on 2023-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20231204_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_id',
            field=models.CharField(max_length=30, null=True, verbose_name='user_id'),
        ),
    ]
