# Generated by Django 4.2.7 on 2023-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_type', models.CharField(max_length=30, verbose_name='manager_type')),
                ('manager_name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='manager_name')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
    ]
